/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#f3ffca",
        "on-error-container": "#ffa8a3",
        "surface-container": "#191923",
        "surface-variant": "#252531",
        "tertiary-dim": "#beee00",
        "background": "#0d0d16",
        "surface-container-low": "#13131c",
        "secondary-fixed": "#ffbdf3",
        "secondary-container": "#a900a9",
        "on-secondary-fixed-variant": "#920091",
        "primary": "#96f8ff",
        "inverse-on-surface": "#55545e",
        "on-background": "#f2effb",
        "surface-container-lowest": "#000000",
        "surface-container-high": "#1f1f2a",
        "tertiary-container": "#cafd00",
        "primary-container": "#00f1fd",
        "outline": "#76747f",
        "on-primary-container": "#00565a",
        "surface": "#0d0d16",
        "secondary-fixed-dim": "#ffa6f3",
        "surface-bright": "#2b2b38",
        "primary-fixed": "#00f1fd",
        "error": "#ff716c",
        "tertiary-fixed-dim": "#beee00",
        "on-secondary": "#400040",
        "primary-dim": "#00e2ed",
        "inverse-primary": "#006a6f",
        "error-container": "#9f0519",
        "on-tertiary-fixed-variant": "#526900",
        "on-tertiary-container": "#4a5e00",
        "error-dim": "#d7383b",
        "on-secondary-fixed": "#620061",
        "on-error": "#490006",
        "on-tertiary": "#516700",
        "surface-tint": "#96f8ff",
        "secondary-dim": "#ff51fa",
        "on-secondary-container": "#fff5f9",
        "inverse-surface": "#fcf8ff",
        "surface-container-highest": "#252531",
        "surface-dim": "#0d0d16",
        "on-surface": "#f2effb",
        "tertiary-fixed": "#cafd00",
        "on-primary-fixed": "#004145",
        "on-primary": "#005f64",
        "outline-variant": "#484751",
        "on-surface-variant": "#acaab5",
        "secondary": "#ff51fa",
        "on-primary-fixed-variant": "#006065",
        "on-tertiary-fixed": "#3a4a00",
        "primary-fixed-dim": "#00e2ed"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
